### ISSUE TITLE
TOTP validation?

### ISSUE THREAD

**Issue by gee-forr** [looorent/keycloak-admin-ruby#35]
Hey there,

I know that the gem doesn't support validating TOTP's, but would you @looorent consider this useful functionality? 

We're planning to implement TOTP checks for dangerous operations in our app, and it would be great if we could simply do something along the lines as below within our app:

```ruby
kc_user = KeycloakAdmin.realm("my_realm").users.get(current_user.keycloak_id)
otp_ok = kc_user.totp_ok?(params[:totp]) # => true or false, depending...
```

Would you see this as a valuable feature to add? If so, we would like potentially issue a PR?

**Comment by looorent** [comment]
Hello @gee-forr,

Could you please clarify what you mean by "validating TOTP's"?

As this library is a Ruby client for the Keycloak Admin REST API, the general guideline is that a feature can only be added if it represents functionality provided by the Keycloak Admin REST API.

If you mean "checking if the Keycloak user has OTP credentials," this can already be done using UserRepresentation. For example:
```ruby
kc_user = KeycloakAdmin.realm("my_realm").users.get(current_user.keycloak_id)
otp_ok = kc_user.totp
```

If you are referring to verifying an OTP code against the server, I do not believe this is a functionality provided by the Keycloak Admin REST API. However, I could be mistaken (see [Keycloak REST API Documentation](https://www.keycloak.org/docs-api/latest/rest-api/index.html)).

Alternatively, you could retrieve the user's credentials of the `totp` type. This is a feature that could potentially be added to the library since the endpoint exists in the API. You would get something like:
```json
"credentialData": {
  "subType": "totp", 
  "digits": 6, 
  "counter": 0,
  "period": 30,
  "algorithm": "HmacSHA1"
}
```

Using this information, along with the OTP Policy (in the `RealmRepresentation`) and possibly some custom (or existing?) endpoints, it might be feasible (see [Keycloak Discussion](https://github.com/keycloak/keycloak/discussions/12350)). However, this alternative is beyond the scope of this library.

Maybe simply calling the `/protocol/openid-connect/token` by providing the `otp` argument is also a valid option, but I never tested it.

**Comment by gee-forr** [comment]
Hey @looorent - thanks so much for the detailed reply.

You are correct in that I wish to verify an OTP controlled by keycloak via the API, and not have to redirect to the keycloak UI to verify the OTP.

As to your point around it not being an admin-focussed function, and therefore not suitable for this library, I agree with that too.

P.S - thanks for the link to that keycloak discussion, it was useful :)
